# Generated by Django 4.1.2 on 2022-11-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_category_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_name',
        ),
    ]
